[project]
name = "fletdemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flet-cli>=0.25.2",
    "flet>=0.25.2",
    "flet-desktop>=0.25.2",
    "flet-web>=0.25.2",
]
